version: '3.5'

services:
  postgres:
    container_name: devspace
    image: postgres
    environment:
      POSTGRES_DB: devspacedb
      POSTGRES_USER: ${PGUSER:-devspaceuser}
      POSTGRES_PASSWORD: ${PGPASSWORD:-devspacepass}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

volumes:
  postgres: